### ISSUE TITLE
Request peer dependency

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-js#6]
I think this is problematic to have 'request' as a peer dependency. Maybe we should switch to an http request library that support Promises without such peer dependency. 

Like axios?

**Comment by jduthon** [comment]
👍  
Axios is also more popular.
Only alternative I could think of would be a universal fetch, but I believe axios is also really famous and seems like fetch should not land to node ever, so since our main target is node I would say axios is the one that makes the most sense.
